### ISSUE TITLE
when installing there is the error "object 'install_packages' not found"

### ISSUE THREAD

**Issue by benny-hal** [renozao/repotools#3]

**Comment by benny-hal** [comment]
Step #1: * removing ‘/usr/local/lib/R/site-library/repotools’
Step #1: ERROR: lazy loading failed for package ‘repotools’
Step #1: Error : unable to load R code in package ‘repotools’
Step #1: object 'install_packages' not found
Step #1: Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :

**Comment by benny-hal** [comment]
@renozao can i fix this?

**Comment by renozao** [comment]
This was fixed in 3acf0b38 and 9817c35
